name: Mirror to Codeberg

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * 0'
  push:
    branches:
      - main

permissions:
  contents: read    # you’re only reading from GH

jobs:
  mirror:
    runs-on: ubuntu-latest

    # pull your Codeberg API token from secrets
    env:
      CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git author
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add Codeberg remote & push
        run: |
          REMOTE="https://${CODEBERG_TOKEN}@codeberg.org/${{ github.repository }}.git"
          git remote add codeberg "$REMOTE" || true
          git push codeberg --all --force
          git push codeberg --tags --force
